nome = str(input("Digite seu nome: "))
print(f"Total de letras do seu nome: {len(nome)}")
print(f"Seu nome em maisculas é: {nome.upper()}")
print(f"A primeira letra do seu nome é: {nome[0]}")
print(f"A ultima letra do seu nome é: {nome[-1]}")
print(f"Seu nome tem a letra A na posição {nome.find('a'.upper())}")
print(f"O código da letra A é: {ord('A')}")
print(f"A letra de código 65 é: {chr(65)}")
print(f"seu nome ao contrário é: {nome[::-1]}")